### ISSUE TITLE
Program auto exits after a few seconds

### ISSUE THREAD

**Issue by Du-Li** [Trendyol/go-kafka-connect-couchbase#33]
**Describe the bug**
About 5 seconds after starting go-kafka-connect-couchbase connector, the health check failed and the connector auto exited.

**To Reproduce**
1. extend the example main.go to print the received cb-dcp events
2. copy the example main.go and config.yml to an ubuntu box
3. run the code like `go run main.go`

{"level":"debug","time":"2023-03-21T04:39:33Z","message":"vbucket discovery opened with membership type: static"}
{"level":"info","time":"2023-03-21T04:39:33Z","message":"member: 1/1, vbucket range: 0-1023"}
{"level":"debug","time":"2023-03-21T04:39:33Z","message":"loaded checkpoint"}
{"level":"debug","time":"2023-03-21T04:39:33Z","message":"stream started"}
{"level":"debug","time":"2023-03-21T04:39:33Z","message":"started checkpoint schedule"}
{"level":"info","time":"2023-03-21T04:39:33Z","message":"dcp stream started"}
{"level":"info","time":"2023-03-21T04:39:33Z","message":"metric middleware registered on path /metrics"}
{"level":"info","time":"2023-03-21T04:39:33Z","message":"api starting on port 8080"}
{"level":"debug","time":"2023-03-21T04:39:43Z","message":"no need to save checkpoint"}
{"level":"error","error":"context deadline exceeded","time":"2023-03-21T04:39:48Z","message":"health check failed"}
{"level":"debug","time":"2023-03-21T04:39:48Z","message":"vbucket discovery closed"}
{"level":"debug","time":"2023-03-21T04:39:48Z","message":"no need to save checkpoint"}
{"level":"debug","time":"2023-03-21T04:39:48Z","message":"stopped checkpoint schedule"}
{"level":"debug","time":"2023-03-21T04:39:49Z","message":"stream stopped"}
{"level":"debug","time":"2023-03-21T04:39:49Z","message":"api stopped"}
{"level":"debug","time":"2023-03-21T04:39:49Z","message":"dcp connection closed
{"level":"debug","time":"2023-03-21T04:39:49Z","message":"connections closed
{"level":"info","time":"2023-03-21T04:39:49Z","message":"dcp stream closed"}

**Expected behavior**
It's expected to continuously print the cb dcp events as long as a workload is fed into cb.

**Screenshots**
N/A

**Version (please complete the following information):**
 - OS: Linux ubuntu-box 5.4.231-137.341.amzn2.x86_64
 - Golang version: go1.18.1 linux/amd64
 - Couchbase: Community Edition 6.5.0 build 4966
 - Kafka: 3.3.1

**Additional context**

**Comment by mhmtszr** [comment]
Hello @Du-Li, it seems there was a dcp checkpoint timeout, could you please try to increase the checkpoint timeout? I will share an example config. Also, which version of go-kafka-connect-couchbase have you used? 

```
dcp:
  ...
checkpoint:
  timeout: 100s
  type: manual
```

**Comment by erayarslan** [comment]
@Du-Li its not about checkpoint. i think its about our default healthCheck timeout which is 5 seconds. you can check it from [here](https://github.com/Trendyol/go-dcp-client#configuration)
can you increase and retry?
for example
```
healthCheck:
  timeout: 30s
```
thank you for feedbacks.

**Comment by erayarslan** [comment]
health check periodically sending ping request to couchbase to ensure its alive.
if ping gonna fail or timeout, we are shutting down everything.
logic is [here](https://github.com/Trendyol/go-dcp-client/blob/master/dcp/client.go#L74)
somehow your cluster didnt response client's ping request.
any additional configuration about your cluster can you provide to me? so i can try to reproduce on that environment.

**Comment by Du-Li** [comment]
The program exited by the healthCheck interval+timeout despite a workload continuously updating CB and the program itself printing the right dcp events.

**Comment by erayarslan** [comment]
i think i understand the issue. your cluster running on aws right? when we send ping request, we are controlling all kind of couchbase service like memd, mgmt, n1ql, fts, capi ... if your network policy not allowing one of these, ping gonna fail probably.

**Comment by Du-Li** [comment]
I see. I am running the connector and kafka in EKS while the CB cluster out EKS. What kind of network policy is needed to make ping work?

**Comment by Du-Li** [comment]
yep I can't agree more. as long as it is able to receive dcp events, it should be considered healthy. no need for comprehensive checking.

**Comment by erayarslan** [comment]
[v0.0.22](https://github.com/Trendyol/go-kafka-connect-couchbase/releases/tag/v0.0.22) ping only needs memd (default port: 11210) and mnmt (default port: 8091) services.
if your network policy allowing these ports, problem should be solved. can you retry?

**Comment by Du-Li** [comment]
@erayarslan health check still failed after interval+timeout time. From the same machine the program was run, I tried `telnet` on the two ports to one of the CB servers and they worked.

> {"level":"info","time":"2023-03-21T18:35:41Z","message":"api starting on port 8080"}
> {"level":"error","error":"context deadline exceeded","time":"2023-03-21T18:35:56Z","message":"health check failed"}

**Comment by Du-Li** [comment]
yes I am very sure. following is part of my go.mod file.

`
require (
	github.com/Trendyol/go-kafka-connect-couchbase v0.0.22
	github.com/gookit/config/v2 v2.2.1
)

require (
	github.com/Trendyol/go-dcp-client v0.0.24 // indirect
`

**Comment by erayarslan** [comment]
i cannot reproduce your behaviour so i expose healthcheck disable/enable config. with v0.0.23 u can disable healthcheck like
```
healthCheck:
  enabled: false
```

**Comment by Du-Li** [comment]
@erayarslan Thanks. That worked.

**Comment by erayarslan** [comment]
thank you so much for contribution 🥳
